project:
  type: website
  output-dir: docs

website:
  title: "cbhyphen.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cbhyphen
      # - icon: twitter
      #   href: https://twitter.com

format:
  html:
    theme: litera
    css: styles.css



